### PR TITLE
updated looks_like_ris to comply with specs

### PR DESCRIPTION
**Pull request by bisen**

### CODE REVIEW

**Comment by bisen** [comment]
I also think we should keep it. 

I wrote the original method thinking that TY is required and every record has to start with it, but after we receive that email last week, I checked Wikipedia again. It is a little ambiguously worded. They say: **Except for TY - and ER -, order of tags is free and their inclusion is optional.** I thought it could be interpreted as TY (if exists) has to be at the beginning of a record, and created the pull request.

Just now, to be absolutely certain, I looked at the primary source Wikipedia references again (https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp) and there it clearly says that every record _**must**_ start with a TY tag. Exact quote: **Note that the required tags are "TY" which must be the first tag in the reference, and "ER" which must be the last tag in the reference.**

**Comment by jensjap** [comment]
Well...it also said that 'ER  - ' was required...which is what we are checking. Isn't that the point of this method: to ensure the existence of the required tags.

**Comment by jensjap** [comment]
so to be clear...if the purpose of this method is to check for the correctness/consistency of a potential RIS file...then it would make sense to make sure that the required fields are present (TY and ER) and that they are in the proper place (first and last, respectively).

I think you were right before...to not only check for their existence but also to ensure that for every 'TY' there was a corresponding 'ER' tag. What was missing is ensuring that 'ER' was the last for each record (or simply very last line in the entire file) to ensure that it is a valid RIS file.

**Comment by jensjap** [comment]
In any case...was this method the cause for the server error though. I would have thought that a malformed RIS file would simply return false here and move on. Meaning the exception would be raised somewhere else?

**Comment by bisen** [comment]
Yes, this was definitely the main issue. There are 3 file types that we check for and if none of them is a match, an exception is raised and we don't really handle that gracefully. So maybe we should display an error and fall back. 

Also, you're correct on checking for 'ER  -' being the last record, I haven't included in the original version of this method, but now that I've written it, we can include that check as well.

**Comment by jensjap** [comment]
okay...so let's do those things. I'm gonna close this merge request and just resubmit with the following: 

1. Check that 'ER  - ' is the last tag
1. Proper handling when the file submitted doesn't conform to any of the file types we handle.

**Pull request closed without merging**
